-- AlterTable
ALTER TABLE `media` ADD COLUMN `Actor4` VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN `Director` VARCHAR(255) NOT NULL DEFAULT '',
    MODIFY `Actor1` VARCHAR(255) NOT NULL DEFAULT '',
    MODIFY `Actor2` VARCHAR(255) NOT NULL DEFAULT '',
    MODIFY `Actor3` VARCHAR(255) NOT NULL DEFAULT '';
